definitions:
  controller.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  controller.Bytes:
    items: {}
    type: array
  seismic_core.Geometry:
    properties:
      cubeid:
        type: string
      dim0:
        items:
          type: integer
        type: array
      dim1:
        items:
          type: integer
        type: array
      dim2:
        items:
          type: integer
        type: array
    type: object
  store.Manifest:
    properties:
      cubeid:
        type: string
      dim0:
        items:
          type: integer
        type: array
      dim1:
        items:
          type: integer
        type: array
      dim2:
        items:
          type: integer
        type: array
    type: object
info:
  contact:
    name: Equinor
  description: The Seismic Cloud Api
  license:
    name: proprietary
  title: Seismic Cloud Api
paths:
  /manifest/{manifest_id}:
    get:
      description: get manifest file
      operationId: download_manifest
      parameters:
      - description: File ID
        in: path
        name: manifest_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: byte stream
          schema:
            $ref: '#/definitions/store.Manifest'
        "404":
          description: Manifest not found
          schema:
            type: string
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
      security:
      - ApiKeyAuth: []
      tags:
      - manifest
    post:
      description: post manifest
      parameters:
      - description: File ID
        in: path
        name: manifest_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: byte stream
          schema:
            $ref: '#/definitions/store.Manifest'
        "502":
          description: Internal Server Error
          schema:
            type: string
  /stitch/{manifest_id}/{surface_id}:
    get:
      description: post surface query to stitch
      operationId: stitch
      parameters:
      - description: The id of a manifest
        in: path
        name: manifest_id
        required: true
        type: string
      - description: The id of a surface
        in: path
        name: surface_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: byte stream
          schema:
            type: string
        "400":
          description: Surface id not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
      security:
      - ApiKeyAuth: []
      tags:
      - stitch
  /stitch/{manifest_id}/dim/{dim}:
    get:
      description: post surface query to stitch
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Bytes'
        "400":
          description: Surface id not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /surface/:
    get:
      description: get list of available surfaces
      operationId: list_surfaces
      produces:
      - application/json
      responses:
        "200":
          description: byte stream
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
      security:
      - ApiKeyAuth: []
      tags:
      - surface
  /surface/{surface_id}:
    get:
      description: get surface file
      operationId: download_surface
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: byte stream
          schema:
            type: string
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
      security:
      - ApiKeyAuth: []
      tags:
      - surface
    post:
      consumes:
      - application/octet-stream
      description: post surface file
      operationId: upload_surface
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: byte stream
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
      security:
      - ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Operations for manifests
  name: manifest
- description: Operations for surfaces
  name: surface
- description: Stitch together cube data
  name: stitch
