definitions:
  controller.APIError:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
  controller.Bytes:
    items: {}
    type: array
info:
  contact: {}
  license: {}
paths:
  /manifest/{manifest_id}:
    get:
      description: get manifest file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Bytes'
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /stitch/{manifest_id}/{surface_id}:
    get:
      description: post surface query to stitch
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Bytes'
        "400":
          description: Surface id not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /surface/:
    get:
      description: get list of available surfaces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
  /surface/{surface_id}:
    get:
      description: get surface file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Bytes'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "502":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
    post:
      consumes:
      - application/octet-stream
      description: post surface file
      parameters:
      - description: File ID
        in: path
        name: surfaceID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Bytes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.APIError'
swagger: "2.0"
