os: linux
dist: xenial
sudo: required
compiler: clang

matrix:
  fast_finish: true
  include:
    - language: python
      python: 3.7
    - language: python
      python: 3.6
    - language: c++
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
            - libomp-dev

script:
    - if [[ -n "${TRAVIS_PYTHON_VERSION+1}" ]]; then
        pushd core/ingestion/scan &&
        pip install -r requirements-dev.txt &&
        python setup.py test && popd;
        pushd core/ingestion/upload &&
        pip install -r requirements-dev.txt &&
        python setup.py test && popd;
      fi

    - if [[ -z $TRAVIS_PYTHON_VERSION ]]; then
        mkdir build &&
        pushd build &&
        cmake ../core -DCMAKE_BUILD_TYPE=Release &&
        make &&
        ctest --output-on-failure;
      fi
