trigger:
  - master
  - release

pool:
  vmImage: 'ubuntu-18.04'

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  GOVERSION: '1.13.4'
  TEST_COVERAGE_LIMIT: 35

jobs:
  - job: Build_Core
    steps:
      - script: |
          wget https://github.com/fmtlib/fmt/releases/download/6.0.0/fmt-6.0.0.zip
          unzip fmt-6.0.0.zip
          mkdir -p fmt-6.0.0/build
          cd fmt-6.0.0/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
          sudo make install -j2
        displayName: 'Build fmt'
      - script: |
          sudo apt-get install -y libgnutls-dev libcurl4-gnutls-dev
          sudo pip install scikit-build pybind11
          mkdir build
          cd build
          cmake ../core -DCMAKE_BUILD_TYPE=Release
        displayName: 'Setup seismic-cloud'

      - script: |
          make
        displayName: 'Build seismic-cloud'
        workingDirectory: build

      - script: |
          ctest --output-on-failure
        displayName: 'Test seismic-cloud'
        workingDirectory: build

  - job: Build_API
    container: b1
    variables:
      GOPATH: '$(system.defaultWorkingDirectory)/gopath'
      TEST_COVERAGE_LIMIT: 35
    steps:
      - bash: |
          echo "##vso[task.prependpath]$(GOPATH)/bin"
        displayName: Update PATH

      - task: GoTool@0
        inputs:
          version: '$(GOVERSION)'
          goPath: '$(GOPATH)'
          goBin: '$(GOPATH)/bin'
      - script: |
          sudo apt-get install -y protobuf-compiler
          go get -u github.com/golang/protobuf/protoc-gen-go
          protoc -I ../protos ../protos/core.proto --go_out=plugins=grpc:proto
        displayName: 'Generating grpc client stubs'
        workingDirectory: api
      - script: |
          go get github.com/swaggo/swag/cmd/swag
          swag init
        workingDirectory: api
        displayName: 'Generate OpenAPI spec'

      - script: |
          git config --global url."https://$(GITHUB_TOKEN):x-oauth-basic@github.com/equinor".insteadOf "https://github.com/equinor"
          go build
        workingDirectory: api
        displayName: 'Build api'

  - job: Run_unit_tests
    steps:
      - bash: |
          echo "##vso[task.prependpath]$(GOPATH)/bin"
        displayName: Update PATH

      - task: GoTool@0
        inputs:
          version: '$(GOVERSION)'
          goPath: '$(GOPATH)'
          goBin: '$(GOPATH)/bin'

      - script: |
          git config --global url."https://$(GITHUB_TOKEN):x-oauth-basic@github.com/equinor".insteadOf "https://github.com/equinor"
          go test -race ./...
        workingDirectory: api
        displayName: 'Run unit tests'

  - job: Test_coverage
    steps:
      - bash: |
          echo "##vso[task.prependpath]$(GOPATH)/bin"
        displayName: Update PATH

      - task: GoTool@0
        inputs:
          version: '$(GOVERSION)'
          goPath: '$(GOPATH)'
          goBin: '$(GOPATH)/bin'

      - script: |
          git config --global url."https://$(GITHUB_TOKEN):x-oauth-basic@github.com/equinor".insteadOf "https://github.com/equinor"
          go get github.com/jstemmer/go-junit-report
          go get github.com/axw/gocov/gocov
          go get github.com/AlekSi/gocov-xml
          go get github.com/matm/gocov-html
          go test -v -coverprofile=coverage.txt -covermode count 2>&1 ./... | go-junit-report > report.xml
          gocov convert coverage.txt > coverage.json
          gocov-xml < coverage.json > coverage.xml
          mkdir -p coverage
          gocov-html < coverage.json > coverage/index.html
        displayName: 'Generate test coverage report'
        workingDirectory: api

      - task: PublishCodeCoverageResults@1
        condition: always()
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
          reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage

      - script: |
          COVERAGE=`go tool cover -func coverage.txt | tail -n 1 | awk '{print substr($3, 1, length($3)-1)}'`
          COVERAGE=${COVERAGE%.*}
          echo "Test coverage limit:" $TEST_COVERAGE_LIMIT%
          echo "Test coverage:" $COVERAGE%

          if (( COVERAGE < TEST_COVERAGE_LIMIT )); then
              exit 1
          fi
        displayName: 'Coverage limit'
        workingDirectory: api

  - job: Integration_tests
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - script: |
          docker-compose build --build-arg GITHUB_TOKEN=$(GITHUB_TOKEN)
        # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: 'Build docker images'
      - script: |
          GITHUB_TOKEN=$(GITHUB_TOKEN) docker-compose -f tests/docker-compose.yml up --build --exit-code-from test
        # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: 'Run integration tests'
      - script: |
          echo $(ACRPASSWD)|docker login -u lambdaville lambdaville.azurecr.io --password-stdin
          docker-compose push
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: 'Push docker images'

schedules:
  - cron: '0 6 * * *'
    displayName: nightly build
    branches:
      include:
        - master
    always: true
