version: '3.0'
services:

  corestub:
    image: lambdaville.azurecr.io/corestub:latest
    build: 
      context: corestub
      args:
        - GITHUB_TOKEN

  api:
    image: lambdaville.azurecr.io/api:latest
    build: api
