version: '3.0'
services:
  manifest:
    image: oneseismic.azurecr.io/base:${VERSION:-latest}
    build:
      context: .
      dockerfile: core/Dockerfile
    command: [
        "oneseismic-manifest",
        "--source",  "tcp://api:6143",
        "--sink",    "tcp://*:6142",
        "--control", "tcp://0.0.0.0:6141",
        "--fail",    "tcp://api:6140",
        "--redis",   "storage:6379",
    ]
    depends_on:
      - api
  fragment:
    image: oneseismic.azurecr.io/base:${VERSION:-latest}
    build:
      context: .
      dockerfile: core/Dockerfile
    command: [
        "oneseismic-fragment",
        "--source",  "tcp://manifest:6142",
        "--sink",    "tcp://0.0.0.0:6144",
        "--control", "tcp://0.0.0.0:6141",
        "--fail",    "tcp://api:6140",
        "--redis",   "storage",
    ]
    depends_on:
      - api
      - manifest
      - storage

  api:
    image: oneseismic.azurecr.io/api:${VERSION:-latest}
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '8080:8080'
    command: [
        "oneseismic-query",
    ]
    environment:
      - HOST_ADDR=0.0.0.0:8080
      - AUTHSERVER
      - AUDIENCE
      - STORAGE_URL
      - CLIENT_ID
      - CLIENT_SECRET
      - LOG_LEVEL
      - REDIS_URL=storage:6379
      - BIND=tcp://*:6143
      - SIGN_KEY

  storage:
    image: redis
