name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Action - GolangCI Lint
      uses: matoous/golangci-lint-action@v1.0.0
